/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_Main */

#ifndef _Included_app_Main
#define _Included_app_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_Main
 * Method:    fact
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_app_Main_fact
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
